version: "3.8"

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.template
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
    command: python app/main.py

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: parking
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    # - frontend

volumes:
  db_data: