services:
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.template
    ports:
      - "5173:5173" # Host port 5173 maps to container port 3000 (Vite's default dev port)
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules # <--- This is crucial for development to prevent host node_modules from overwriting
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8000/ws
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev # <--- THIS IS THE CRITICAL CHANGE

  backend:
    build: ./backend
    env_file:
      - ./backend/.env.template
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - DEBUG_METRICS=1
    command: python app/main.py

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: parking
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
      - node-exporter

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000" # Grafana remains on host port 3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  db_data:
  grafana_data: