services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.template
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - DEBUG_METRICS=1
    command: python app/main.py

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: parking
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      # - frontend -> ini nanti tinggal di uncomment aja

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on: # Tambahkan ini agar Prometheus menunggu backend & node-exporter
      - backend
      - node-exporter # Tambahkan ini

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on: # Tambahkan ini agar Grafana menunggu Prometheus
      - prometheus

  # --- TAMBAHKAN SERVICE NODE EXPORTER INI ---
  node-exporter:
    image: prom/node-exporter
    # HAPUS network_mode: "host"
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude="^/(sys|proc|dev|host|etc)($$|/)"'

volumes:
  db_data:
  grafana_data: